spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    default-schema: prod
    parameters:
      searchPath: classpath:/, classpath:/db/changelog/
  datasource:
    url: jdbc:postgresql://localhost:5454/meteorological_data_db
    password: 2006
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:auto: validate
    open-in-view: false

